alter database <DBNAME> set default_transaction_read_only = on;
BEGIN READ WRITE;
GRANT USAGE ON SCHEMA cd TO <USER>;
GRANT CONNECT ON DATABASE <DBNAME> TO <USER>;
GRANT SELECT ON ALL TABLES IN SCHEMA cd TO <USER>;
COMMIT;