CREATE DATABASE exercises{$DBNAME};
\c exercises{$DBNAME};
GRANT CONNECT ON DATABASE exercises{$DBNAME} TO pgexercises;
GRANT CONNECT ON DATABASE exercises{$DBNAME} TO pgeadmin;
GRANT CREATE ON DATABASE exercises{$DBNAME} to pgeadmin;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;
