CREATE DATABASE exercisesrw0;
GRANT CONNECT ON DATABASE exercisesrw0 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw0 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw0 to pgeadmin;
\c exercisesrw0;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw1;
GRANT CONNECT ON DATABASE exercisesrw1 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw1 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw1 to pgeadmin;
\c exercisesrw1;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw2;
GRANT CONNECT ON DATABASE exercisesrw2 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw2 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw2 to pgeadmin;
\c exercisesrw2;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw3;
GRANT CONNECT ON DATABASE exercisesrw3 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw3 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw3 to pgeadmin;
\c exercisesrw3;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw4;
GRANT CONNECT ON DATABASE exercisesrw4 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw4 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw4 to pgeadmin;
\c exercisesrw4;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw5;
GRANT CONNECT ON DATABASE exercisesrw5 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw5 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw5 to pgeadmin;
\c exercisesrw5;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw6;
GRANT CONNECT ON DATABASE exercisesrw6 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw6 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw6 to pgeadmin;
\c exercisesrw6;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw7;
GRANT CONNECT ON DATABASE exercisesrw7 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw7 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw7 to pgeadmin;
\c exercisesrw7;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw8;
GRANT CONNECT ON DATABASE exercisesrw8 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw8 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw8 to pgeadmin;
\c exercisesrw8;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw9;
GRANT CONNECT ON DATABASE exercisesrw9 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw9 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw9 to pgeadmin;
\c exercisesrw9;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw10;
GRANT CONNECT ON DATABASE exercisesrw10 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw10 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw10 to pgeadmin;
\c exercisesrw10;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw11;
GRANT CONNECT ON DATABASE exercisesrw11 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw11 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw11 to pgeadmin;
\c exercisesrw11;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw12;
GRANT CONNECT ON DATABASE exercisesrw12 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw12 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw12 to pgeadmin;
\c exercisesrw12;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw13;
GRANT CONNECT ON DATABASE exercisesrw13 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw13 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw13 to pgeadmin;
\c exercisesrw13;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw14;
GRANT CONNECT ON DATABASE exercisesrw14 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw14 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw14 to pgeadmin;
\c exercisesrw14;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw15;
GRANT CONNECT ON DATABASE exercisesrw15 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw15 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw15 to pgeadmin;
\c exercisesrw15;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw16;
GRANT CONNECT ON DATABASE exercisesrw16 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw16 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw16 to pgeadmin;
\c exercisesrw16;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw17;
GRANT CONNECT ON DATABASE exercisesrw17 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw17 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw17 to pgeadmin;
\c exercisesrw17;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw18;
GRANT CONNECT ON DATABASE exercisesrw18 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw18 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw18 to pgeadmin;
\c exercisesrw18;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw19;
GRANT CONNECT ON DATABASE exercisesrw19 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw19 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw19 to pgeadmin;
\c exercisesrw19;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw20;
GRANT CONNECT ON DATABASE exercisesrw20 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw20 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw20 to pgeadmin;
\c exercisesrw20;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw21;
GRANT CONNECT ON DATABASE exercisesrw21 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw21 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw21 to pgeadmin;
\c exercisesrw21;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw22;
GRANT CONNECT ON DATABASE exercisesrw22 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw22 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw22 to pgeadmin;
\c exercisesrw22;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw23;
GRANT CONNECT ON DATABASE exercisesrw23 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw23 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw23 to pgeadmin;
\c exercisesrw23;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw24;
GRANT CONNECT ON DATABASE exercisesrw24 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw24 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw24 to pgeadmin;
\c exercisesrw24;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw25;
GRANT CONNECT ON DATABASE exercisesrw25 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw25 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw25 to pgeadmin;
\c exercisesrw25;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw26;
GRANT CONNECT ON DATABASE exercisesrw26 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw26 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw26 to pgeadmin;
\c exercisesrw26;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw27;
GRANT CONNECT ON DATABASE exercisesrw27 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw27 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw27 to pgeadmin;
\c exercisesrw27;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw28;
GRANT CONNECT ON DATABASE exercisesrw28 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw28 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw28 to pgeadmin;
\c exercisesrw28;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw29;
GRANT CONNECT ON DATABASE exercisesrw29 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw29 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw29 to pgeadmin;
\c exercisesrw29;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw30;
GRANT CONNECT ON DATABASE exercisesrw30 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw30 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw30 to pgeadmin;
\c exercisesrw30;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw31;
GRANT CONNECT ON DATABASE exercisesrw31 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw31 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw31 to pgeadmin;
\c exercisesrw31;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw32;
GRANT CONNECT ON DATABASE exercisesrw32 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw32 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw32 to pgeadmin;
\c exercisesrw32;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw33;
GRANT CONNECT ON DATABASE exercisesrw33 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw33 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw33 to pgeadmin;
\c exercisesrw33;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw34;
GRANT CONNECT ON DATABASE exercisesrw34 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw34 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw34 to pgeadmin;
\c exercisesrw34;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw35;
GRANT CONNECT ON DATABASE exercisesrw35 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw35 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw35 to pgeadmin;
\c exercisesrw35;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw36;
GRANT CONNECT ON DATABASE exercisesrw36 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw36 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw36 to pgeadmin;
\c exercisesrw36;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw37;
GRANT CONNECT ON DATABASE exercisesrw37 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw37 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw37 to pgeadmin;
\c exercisesrw37;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw38;
GRANT CONNECT ON DATABASE exercisesrw38 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw38 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw38 to pgeadmin;
\c exercisesrw38;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw39;
GRANT CONNECT ON DATABASE exercisesrw39 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw39 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw39 to pgeadmin;
\c exercisesrw39;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw40;
GRANT CONNECT ON DATABASE exercisesrw40 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw40 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw40 to pgeadmin;
\c exercisesrw40;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw41;
GRANT CONNECT ON DATABASE exercisesrw41 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw41 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw41 to pgeadmin;
\c exercisesrw41;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw42;
GRANT CONNECT ON DATABASE exercisesrw42 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw42 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw42 to pgeadmin;
\c exercisesrw42;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw43;
GRANT CONNECT ON DATABASE exercisesrw43 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw43 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw43 to pgeadmin;
\c exercisesrw43;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw44;
GRANT CONNECT ON DATABASE exercisesrw44 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw44 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw44 to pgeadmin;
\c exercisesrw44;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw45;
GRANT CONNECT ON DATABASE exercisesrw45 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw45 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw45 to pgeadmin;
\c exercisesrw45;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw46;
GRANT CONNECT ON DATABASE exercisesrw46 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw46 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw46 to pgeadmin;
\c exercisesrw46;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw47;
GRANT CONNECT ON DATABASE exercisesrw47 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw47 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw47 to pgeadmin;
\c exercisesrw47;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw48;
GRANT CONNECT ON DATABASE exercisesrw48 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw48 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw48 to pgeadmin;
\c exercisesrw48;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw49;
GRANT CONNECT ON DATABASE exercisesrw49 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw49 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw49 to pgeadmin;
\c exercisesrw49;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw50;
GRANT CONNECT ON DATABASE exercisesrw50 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw50 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw50 to pgeadmin;
\c exercisesrw50;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw51;
GRANT CONNECT ON DATABASE exercisesrw51 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw51 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw51 to pgeadmin;
\c exercisesrw51;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw52;
GRANT CONNECT ON DATABASE exercisesrw52 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw52 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw52 to pgeadmin;
\c exercisesrw52;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw53;
GRANT CONNECT ON DATABASE exercisesrw53 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw53 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw53 to pgeadmin;
\c exercisesrw53;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw54;
GRANT CONNECT ON DATABASE exercisesrw54 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw54 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw54 to pgeadmin;
\c exercisesrw54;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw55;
GRANT CONNECT ON DATABASE exercisesrw55 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw55 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw55 to pgeadmin;
\c exercisesrw55;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw56;
GRANT CONNECT ON DATABASE exercisesrw56 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw56 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw56 to pgeadmin;
\c exercisesrw56;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw57;
GRANT CONNECT ON DATABASE exercisesrw57 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw57 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw57 to pgeadmin;
\c exercisesrw57;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw58;
GRANT CONNECT ON DATABASE exercisesrw58 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw58 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw58 to pgeadmin;
\c exercisesrw58;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw59;
GRANT CONNECT ON DATABASE exercisesrw59 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw59 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw59 to pgeadmin;
\c exercisesrw59;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw60;
GRANT CONNECT ON DATABASE exercisesrw60 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw60 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw60 to pgeadmin;
\c exercisesrw60;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw61;
GRANT CONNECT ON DATABASE exercisesrw61 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw61 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw61 to pgeadmin;
\c exercisesrw61;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw62;
GRANT CONNECT ON DATABASE exercisesrw62 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw62 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw62 to pgeadmin;
\c exercisesrw62;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw63;
GRANT CONNECT ON DATABASE exercisesrw63 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw63 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw63 to pgeadmin;
\c exercisesrw63;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw64;
GRANT CONNECT ON DATABASE exercisesrw64 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw64 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw64 to pgeadmin;
\c exercisesrw64;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw65;
GRANT CONNECT ON DATABASE exercisesrw65 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw65 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw65 to pgeadmin;
\c exercisesrw65;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw66;
GRANT CONNECT ON DATABASE exercisesrw66 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw66 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw66 to pgeadmin;
\c exercisesrw66;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw67;
GRANT CONNECT ON DATABASE exercisesrw67 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw67 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw67 to pgeadmin;
\c exercisesrw67;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw68;
GRANT CONNECT ON DATABASE exercisesrw68 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw68 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw68 to pgeadmin;
\c exercisesrw68;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw69;
GRANT CONNECT ON DATABASE exercisesrw69 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw69 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw69 to pgeadmin;
\c exercisesrw69;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw70;
GRANT CONNECT ON DATABASE exercisesrw70 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw70 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw70 to pgeadmin;
\c exercisesrw70;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw71;
GRANT CONNECT ON DATABASE exercisesrw71 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw71 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw71 to pgeadmin;
\c exercisesrw71;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw72;
GRANT CONNECT ON DATABASE exercisesrw72 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw72 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw72 to pgeadmin;
\c exercisesrw72;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw73;
GRANT CONNECT ON DATABASE exercisesrw73 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw73 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw73 to pgeadmin;
\c exercisesrw73;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw74;
GRANT CONNECT ON DATABASE exercisesrw74 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw74 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw74 to pgeadmin;
\c exercisesrw74;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw75;
GRANT CONNECT ON DATABASE exercisesrw75 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw75 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw75 to pgeadmin;
\c exercisesrw75;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw76;
GRANT CONNECT ON DATABASE exercisesrw76 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw76 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw76 to pgeadmin;
\c exercisesrw76;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw77;
GRANT CONNECT ON DATABASE exercisesrw77 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw77 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw77 to pgeadmin;
\c exercisesrw77;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw78;
GRANT CONNECT ON DATABASE exercisesrw78 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw78 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw78 to pgeadmin;
\c exercisesrw78;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw79;
GRANT CONNECT ON DATABASE exercisesrw79 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw79 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw79 to pgeadmin;
\c exercisesrw79;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw80;
GRANT CONNECT ON DATABASE exercisesrw80 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw80 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw80 to pgeadmin;
\c exercisesrw80;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw81;
GRANT CONNECT ON DATABASE exercisesrw81 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw81 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw81 to pgeadmin;
\c exercisesrw81;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw82;
GRANT CONNECT ON DATABASE exercisesrw82 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw82 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw82 to pgeadmin;
\c exercisesrw82;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw83;
GRANT CONNECT ON DATABASE exercisesrw83 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw83 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw83 to pgeadmin;
\c exercisesrw83;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw84;
GRANT CONNECT ON DATABASE exercisesrw84 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw84 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw84 to pgeadmin;
\c exercisesrw84;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw85;
GRANT CONNECT ON DATABASE exercisesrw85 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw85 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw85 to pgeadmin;
\c exercisesrw85;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw86;
GRANT CONNECT ON DATABASE exercisesrw86 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw86 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw86 to pgeadmin;
\c exercisesrw86;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw87;
GRANT CONNECT ON DATABASE exercisesrw87 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw87 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw87 to pgeadmin;
\c exercisesrw87;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw88;
GRANT CONNECT ON DATABASE exercisesrw88 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw88 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw88 to pgeadmin;
\c exercisesrw88;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw89;
GRANT CONNECT ON DATABASE exercisesrw89 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw89 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw89 to pgeadmin;
\c exercisesrw89;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw90;
GRANT CONNECT ON DATABASE exercisesrw90 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw90 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw90 to pgeadmin;
\c exercisesrw90;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw91;
GRANT CONNECT ON DATABASE exercisesrw91 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw91 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw91 to pgeadmin;
\c exercisesrw91;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw92;
GRANT CONNECT ON DATABASE exercisesrw92 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw92 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw92 to pgeadmin;
\c exercisesrw92;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw93;
GRANT CONNECT ON DATABASE exercisesrw93 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw93 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw93 to pgeadmin;
\c exercisesrw93;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw94;
GRANT CONNECT ON DATABASE exercisesrw94 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw94 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw94 to pgeadmin;
\c exercisesrw94;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw95;
GRANT CONNECT ON DATABASE exercisesrw95 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw95 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw95 to pgeadmin;
\c exercisesrw95;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw96;
GRANT CONNECT ON DATABASE exercisesrw96 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw96 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw96 to pgeadmin;
\c exercisesrw96;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw97;
GRANT CONNECT ON DATABASE exercisesrw97 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw97 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw97 to pgeadmin;
\c exercisesrw97;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw98;
GRANT CONNECT ON DATABASE exercisesrw98 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw98 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw98 to pgeadmin;
\c exercisesrw98;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;

CREATE DATABASE exercisesrw99;
GRANT CONNECT ON DATABASE exercisesrw99 TO pgexercises;
GRANT CONNECT ON DATABASE exercisesrw99 TO pgeadmin;
GRANT CREATE ON DATABASE exercisesrw99 to pgeadmin;
\c exercisesrw99;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgexercises;
REVOKE ALL PRIVILEGES ON SCHEMA PUBLIC FROM pgeadmin;
